services:
  - type: background
    name: render-test
    runtime: python
    repo: https://github.com/LEONARDOSUSA/Botini5M
    branch: diagnostico-render
    buildCommand: pip install -r requirements.txt
    startCommand: python app_test.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
